# Imagen base fija
FROM python:3.12-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar solo requirements para aprovechar cache
COPY requirements-dev.txt /app/requirements-dev.txt

# Instalar dependencias de Python
RUN pip install --upgrade pip && \
    pip install django

# Copiar todo el código del backend
COPY . /app

# Variable de entorno para usar configuración de desarrollo
ENV DJANGO_SETTINGS_MODULE=config.settings.development

# Comando por defecto para desarrollo
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
