services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.dev
    image: ${BACKEND_IMAGE}    # sigue usando la variable del .env
    env_file:
      - ../../.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"  # sigue usando la variable del .env
    volumes:
      - ../../backend:/app
      
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
    image: ${FRONTEND_IMAGE}
    env_file:
      - ../../.env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ../../frontend:/app
      - /app/node_modules           # volumen anónimo para preservar node_modules
