services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: mi_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ghcr.io/daviddlv007/infra/backend:latest
    env_file:
      - .env
    environment:
      DJANGO_ALLOWED_HOSTS: ${DOMAIN}
      POSTGRES_DB: mi_db
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      - db
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Host: ${DOMAIN}", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  caddy:
    image: caddy:2
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - static_volume:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
    name: db_data
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
