name: CI/CD - Build, Push & Deploy (prod)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend
  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Frontend build + image
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Set up QEMU & Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail

            REPO_DIR="/home/${{ secrets.EC2_USER }}/prueba-infra-3"

            # Carpetas a desplegar
            DEPLOY_FOLDERS=("infra" "otra_carpeta")  # <-- agregar carpetas aquí

            if [ ! -d "$REPO_DIR/.git" ]; then
                echo ">>> Clonando repo parcialmente con HTTPS"
                git init "$REPO_DIR"
                cd "$REPO_DIR"
                git remote add origin https://x-access-token:${{ secrets.GHCR_TOKEN }}@github.com/${{ github.repository }}.git
                git config core.sparseCheckout true

                # Agregar carpetas del array
                for folder in "${DEPLOY_FOLDERS[@]}"; do
                  echo "$folder/" >> .git/info/sparse-checkout
                done

                git fetch --depth=1 origin main
                git checkout main
            else
                echo ">>> Repo ya existe, actualizando..."
                cd "$REPO_DIR"
                git fetch --all
                git reset --hard origin/main
            fi

            # Ir a infra para despliegue
            cd "$REPO_DIR/infra/compose"

            FRONTEND_IMAGE="ghcr.io/${{ github.repository }}/frontend"
            BACKEND_IMAGE="ghcr.io/${{ github.repository }}/backend"

            echo ">>> Login a GHCR"
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo ">>> Pull imágenes (si existen)"
            docker pull "$FRONTEND_IMAGE:latest" || true
            docker pull "$BACKEND_IMAGE:latest" || true

            echo ">>> Crear volúmenes si no existen"
            docker volume inspect static_volume >/dev/null 2>&1 || docker volume create static_volume
            docker volume inspect caddy_data >/dev/null 2>&1 || docker volume create caddy_data
            docker volume inspect caddy_config >/dev/null 2>&1 || docker volume create caddy_config

            echo ">>> Poblar static_volume con build del frontend"
            docker run --rm -v static_volume:/data "$FRONTEND_IMAGE:latest" \
              sh -c "cp -a /usr/share/nginx/html/. /data/ && chown -R 1000:1000 /data || true && sync"

            echo ">>> Generar archivo .env dinámico"
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > .env
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
            echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env

            echo ">>> Deteniendo contenedores existentes para liberar puertos 80/443 (si existen)"
            docker compose -f docker-compose.prod.yml down || true


            echo ">>> Levantar servicios con Docker Compose v2 (db backend caddy)"
            docker compose -f docker-compose.prod.yml up -d --no-build db backend caddy

            echo ">>> Esperando brevemente a que Caddy obtenga/renueve certificados (si es necesario)..."
            # Caddy gestiona ACME automáticamente; esperar un poco para que cree /data.
            sleep 5

            echo ">>> Limpieza imágenes antiguas"
            docker image prune -af --filter 'until=24h' || true

            echo ">>> Estado backend:"
            docker inspect -f '{{.State.Health.Status}}' $(docker ps --filter ancestor=$BACKEND_IMAGE:latest --format '{{.Names}}' | head -n1) 2>/dev/null || echo "no-healthcheck"

            echo ">>> Deploy finalizado."


