name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # opcional
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Terraform Init
        working-directory: infra/terraform/environments/dev
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: infra/terraform/environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/terraform/environments/dev
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply (solo en push a main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: infra/terraform/environments/dev
        run: terraform apply -input=false -auto-approve tfplan
