name: 'Terraform Drift Detection'

on:
  schedule:
    - cron: '0 8 * * 1-5' # Lunes a Viernes a las 8 AM
  workflow_dispatch:

env:
  TF_VERSION: 1.8.2  # ← CAMBIAR de 1.5.0 a 1.8.2
  AWS_REGION: us-east-1

jobs:
  terraform-drift:
    name: 'Terraform Drift Detection'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3  # ← ACTUALIZAR a v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4  # ← ACTUALIZAR a v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        echo "Initializing backend for drift detection..."
        chmod +x ./infra/terraform/scripts/init-backend.sh
        ./infra/terraform/scripts/init-backend.sh
      working-directory: ./
      
    - name: Check for drift
      run: |
        terraform plan -detailed-exitcode
      working-directory: ./infra/terraform/environments/dev
      continue-on-error: true  # ← Esto ya está bien