name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Nombre del proyecto'
        required: false
      aws_region:
        description: 'Región AWS (override)'
        required: false

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_BUCKET: ${{ secrets.BACKEND_BUCKET }}
      TF_TABLE: ${{ secrets.BACKEND_TABLE }}
      TF_REGION: ${{ github.event.inputs.aws_region || secrets.AWS_REGION || 'us-east-1' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validar secrets requeridos
        run: |
          if [ -z "${TF_BUCKET:-}" ]; then
            echo "ERROR: secret BACKEND_BUCKET no definido. Ejecuta create-backend y guarda BACKEND_BUCKET en Secrets."
            exit 1
          fi
          if [ -z "${TF_TABLE:-}" ]; then
            echo "ERROR: secret BACKEND_TABLE no definido. Ejecuta create-backend y guarda BACKEND_TABLE en Secrets."
            exit 1
          fi
        shell: bash

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.TF_REGION }}

      - name: Validar backend remoto existe
        run: |
          if ! aws s3api head-bucket --bucket "$TF_BUCKET" 2>/dev/null; then
            echo "ERROR: Bucket S3 $TF_BUCKET no existe. Ejecuta create-backend primero."
            exit 1
          fi
          if ! aws dynamodb describe-table --table-name "$TF_TABLE" >/dev/null 2>&1; then
            echo "ERROR: Tabla DynamoDB $TF_TABLE no existe. Ejecuta create-backend primero."
            exit 1
          fi
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Terraform Init (configura backend en S3/DynamoDB)
        run: |
          terraform init \
            -backend-config="bucket=$TF_BUCKET" \
            -backend-config="region=$TF_REGION" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="dynamodb_table=$TF_TABLE" \
            -reconfigure
        working-directory: infra/terraform
        shell: bash

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/terraform
        shell: bash

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
        working-directory: infra/terraform
        shell: bash

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: infra/terraform
        shell: bash
